require("minchan.plugins-setup")
require("minchan.core.options")
require("minchan.core.keymaps")
require("minchan.core.colorschemes")
require("minchan.plugins.lualine")
require("minchan.plugins.telescope")
